import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

const Home: NextPage = () => {
	return (
		<div className='lg:max-w-6xl mx-auto min-h-screen overflow-hidden bg-black'>
			<Head>
				<title>Twitter 2.0</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='grid grid-cols-9'>
				<Sidebar />
				<Feed />
				<Widgets />
				{/* Modal */}
			</main>
		</div>
	)
}

export default Home
